### ISSUE TITLE
Validation results

### ISSUE THREAD

**Issue by YH-2023** [xiaomoguhz/OV-DQUO#1]
When I run validation using the release checkpoints weights, the results do not match those in the paper. why is that?
The results are:
AP（Novel）：45.2
AP（Base）：48.4
AP（All）：47.6

The following are the results of using RN50x4 as the backbone
![image](https://github.com/user-attachments/assets/fb1d12da-e447-4734-a32e-9513383d9f3a)
![image](https://github.com/user-attachments/assets/905ceb80-8890-4518-813b-d40cf425b610)

**Comment by xiaomoguhz** [comment]
@YH-2023 Hi，YH。Thank you for your attention to our work. The reason you were unable to achieve the results mentioned in our paper through direct inference is that the RoQI selection method we discussed in the paper was not utilized during inference. However, this is just a small trick to improve performance, not the main innovation part of our paper. Due to my busy academic schedule, I will organize and update the code during my free time. Thank you again for your attention. 
Best regards, Junjie Wang
