### ISSUE TITLE
Excessive memory usage during training

### ISSUE THREAD

**Issue by YiZhiTangZong** [xiaomoguhz/OV-DQUO#2]
The training process is consuming an excessive amount of memory. I estimate that it will use over 1TB during a single epoch, and it has already triggered an Out-Of-Memory (OOM) kill on my machine. 

I am wondering if this behavior is normal or expected. I suspect that there might be a memory leak.

### Details of the Issue:

While training `bash scripts/OV-COCO/distrain_RN50.sh logs/r50_ovcoco`, every 200 steps in Epoch [0] (indicated by logs like `[200/5131]`), the memory usage increases by approximately 4GB, eventually exhausting all available memory. It appears that completing Epoch [0] could potentially require 1TB of memory.

### Investigation Findings:

I examined the `train_one_epoch()` function in `engine.py` with memory monitoring and discovered the following:

1. After executing `samples = samples.to(device)`, the program's memory usage increases by 0.04GB.
2. Later, after `outputs = model(samples, categories=used_categories, targets=targets)`, memory usage increases by an additional 0.01GB (this occurs once every three cycles).
3. However, deleting all variables at the end of the loop (e.g., `del samples`) does not appear to free up memory immediately.
4. Memory is released at the beginning of the next cycle, decreasing by about 0.04GB. It seems that each cycle can result in a net memory increase of 0.01GB.

### Questions:

1. Where is the rest of the memory being used? My analysis of the `train_one_epoch()` function did not account for such high memory usage. There must be other processes consuming significant memory.
2. What is the purpose of the `del` statement? The memory usage did not change when I deleted these lines of code.
3. Where are the `samples` initially stored? Are they on the CPU or CUDA?

Please share your memory usage during training and verify if there are any memory leaks.

**Comment by xiaomoguhz** [comment]
Hi, @YiZhiTangZong. Thank you for your question and attention to our work. 
Firstly, the device we are running is equipped with 8 GPUs and 256GB of RAM. In addition, we also observed memory growth during the training process, but it did not cause OOM on our server, so we overlooked this situation before. 
We believe that this should be caused by the participation of open world pseudo annotations in the training process. Please give us some time to re-examine the training process to resolve this issue. 
Due to the fact that only I personally maintain this code,the process might not be very fast. I appreciate your understanding and patience.

**Comment by YiZhiTangZong** [comment]
收到。
